### ISSUE TITLE
importChar needs to be dynamic

### ISSUE THREAD

**Issue by zorianak** [zorianak/jadecraft#3]
Right now, importChar is not dynamic - it just loads default data.

From this: https://github.com/zorianak/jadecraft/issues/2

Those same parameters need to be used for importChar, or use the default values of Caligraphy on US-Windrunner (for debug porpoises).

Parse URL params being passed to char.js (for when people bookmark it) or test POST data (for when form is submitted). Likely you can also edit index.js to dynamically load char.js - but that would likely be another issue.

**Comment by zorianak** [comment]
Note that I just mean that char.js shouldn't be taking in hardcoded data

**Comment by vulpineblaze** [comment]
The call to importChar() right now takes URL params. Once I get post data working, it'll easily take post data too. 
As mentioned in #2 , If the desired character doesn't have the property displayed, the pageload fails. 

To clarify, if post data from a form is accepted by the importChar() function, and successfully loads a non-default characters data, is this issue closed? Or is there still something inside that function that needs to be worked on?

**Comment by zorianak** [comment]
Merged this into branch with a few changes. Still doing a bit of cleanup for it.
